server:
  port: 8900

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketsystemdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

jwt:
  secret: balonet

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    enabled: true
    path: /swagger-ui.html
  version: 1